version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/server-go"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/cdn-go"
    schedule:
      interval: "daily"
