name: ZSBRybnik

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Building docker images
        run: npm run build-production-no-cache
