version: "3"
services:
  zsbwebsite:
    container_name: zsbwebsite
    build: ./website
    ports:
      - "5000:5000"
    networks:
      - fullstack
    restart: on-failure
    depends_on:
      - zsbserver
  zsbserver:
    container_name: zsbserver
    build: ./server-go
    ports:
      - "5001:5001"
    depends_on:
      - zsbdatabase
    networks:
      - fullstack
    restart: on-failure
  zsbdatabase:
    container_name: zsbdatabase
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - fullstack
    restart: on-failure
  zsbphpmyadmin:
    container_name: zsbphpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "4000:80"
    networks:
      - fullstack
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "root"
      PMA_HOST: "host.docker.internal"
    restart: on-failure
    depends_on:
      - zsbdatabase

networks:
  fullstack:
    driver: bridge
