apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zsbdatabase
  name: zsbdatabase
spec:
  containers:
  - env:
    - name: MYSQL_PASSWORD
    - name: MYSQL_ROOT_PASSWORD
    - name: MYSQL_USER
    image: mysql:latest
    name: zsbdatabase
    ports:
    - containerPort: 3306
    resources: {}
  restartPolicy: OnFailure
status: {}
