apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zsbftp
  name: zsbftp
spec:
  containers:
  - image: vimagick/vsftpd:latest
    name: zsbftp
    ports:
    - containerPort: 20
    - containerPort: 21
    - containerPort: 30000
    - containerPort: 30001
    - containerPort: 30002
    - containerPort: 30003
    - containerPort: 30004
    - containerPort: 30005
    - containerPort: 30006
    - containerPort: 30007
    - containerPort: 30008
    - containerPort: 30009
    - containerPort: 30010
    resources: {}
  restartPolicy: OnFailure
status: {}
