apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zsbphpmyadmin
  name: zsbphpmyadmin
spec:
  containers:
  - env:
    - name: MYSQL_PASSWORD
    - name: MYSQL_ROOT_PASSWORD
    - name: MYSQL_USER
    - name: PMA_HOST
      value: host.docker.internal
    image: phpmyadmin/phpmyadmin:latest
    name: zsbphpmyadmin
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
