apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zsbredis
  name: zsbredis
spec:
  containers:
  - image: redis:latest
    name: zsbredis
    ports:
    - containerPort: 6379
    resources: {}
  restartPolicy: OnFailure
status: {}
