name: ZSBRybnik

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
      - name: Running build commend
        shell: cmd
        run: npm run build-production-no-cache
