name: ZSBRybnik

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - shell: cmd
        run: npm run build-production-no-cache
